### PR TITLE
Added Project Config support for Entry Types

### PR DESCRIPTION
**Pull request by boboldehampsink**
This uses UID's to identify Entry Types in stead of ID's. Includes a migration to convert existing installations.

### CODE REVIEW

**Comment by boboldehampsink** [comment]
Bump? I am willing to buy a license for this plugin

**Comment by nfourtythree** [comment]
Hey @boboldehampsink 

Sorry about the delay, I happened to leave for vacation for two weeks the day you submitted it and have just returned and getting back to normality.

Will try and get this merged in asap

**Comment by nfourtythree** [comment]
Hey @boboldehampsink 

Thanks for the PR, I have finally had a chance to review it and everything looks good.

Will get a release prepped now!

**Comment by boboldehampsink** [comment]
@nfourtythree thanks! I see you added the 1.2.2 release but it doesn't show up in composer yet. Packagist says 1.2.1 is the latest, so you might want to update packagist? See https://packagist.org/packages/nfourtythree/entriessubset

**Comment by nfourtythree** [comment]
@boboldehampsink turns out packgist was using a legacy integration for auto-updating so hadn't picked up the change. This should be showing the correct version now

**Pull request merged**
